### ISSUE TITLE
Withersoon and ast2500evb failing to build

### ISSUE THREAD

**Issue by shenki** [openbmc/openbmc#601]
https://openpower.xyz/job/openbmc-build/266/

```
01:34:56 Parsing of 1920 .bb files complete (0 cached, 1920 parsed). 2483 targets, 373 skipped, 0 masked, 0 errors.
01:34:57 ERROR: No recipes available for:
01:34:57   /var/lib/jenkins/workspace/openbmc-build/distro/ubuntu/target/witherspoon/openbmc/meta-openbmc-machines/meta-openpower/meta-ibm/meta-witherspoon/recipes-phosphor/skeleton/skeleton.bbappend
```

**Comment by GHF** [comment]
Wasn't this fixed by https://gerrit.openbmc-project.xyz/#/c/620/ ?

**Comment by shenki** [comment]
Lets see if Patrick can merge it for us

**Comment by williamspatrick** [comment]
Merged a few days ago.  Resolved?

**Comment by shenki** [comment]
No, as you can see here Witherspoon is still failing:

https://openpower.xyz/job/openbmc-build/

```
03:10:54 ERROR: No recipes available for:
03:10:54   /var/lib/jenkins/workspace/openbmc-build/distro/ubuntu/target/witherspoon/openbmc/meta-openbmc-machines/meta-openpower/meta-ibm/meta-witherspoon/recipes-phosphor/skeleton/skeleton.bbappend
```

**Comment by GHF** [comment]
to be clear, the error message here differs from #636 because Witherspoon patches skeleton rather than obmc-op-power-control, but it's basically the same failure.
